version: '3.8'
services:
  gowa-bot:
    # GANTI 'username' dengan nama akun GitHub kamu (harus lowercase)
    image: ghcr.io/username/gowa-app:latest
    container_name: gowa_app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      # Mapping file database agar data aman (Persistensi)
      - ./gowa_data.db:/app/gowa_data.db
      - ./uploads:/app/uploads
    # Jika kamu pakai .env, pastikan file ini ada di server
    env_file:
      - .env