name: Build and Deploy

on:
  push:
    branches: 
      - main
      - fullversion # Agar branch ini juga memicu build

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Naik dari v3 ke v4

      - name: Login to GHCR
        uses: docker/login-action@v3 # Naik dari v2 ke v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6 # Naik dari v4 ke v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/gowa-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/gowa
            ./deploy.sh