name: Build and Deploy

on:
  push:
    branches: 
      - main
      - fullversion

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/gowa-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🚀 Mulai proses deployment di server..."
            
            # 1. Pindah ke folder project
            cd ~/gowa
            
            # 2. Muat .bashrc agar token $CR_PAT terbaca
            source ~/.bashrc
            
            # 3. Tarik update docker-compose.yaml dari GitHub
            git fetch origin
            git reset --hard origin/fullversion
            
            # 4. Login ke Registry menggunakan $CR_PAT
            echo "$CR_PAT" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            
            # 5. Tarik image Docker terbaru dan jalankan
            docker compose pull
            docker compose up -d --remove-orphans
            
            # 6. Bersihkan sisa image lama
            docker image prune -f
            echo "✅ Deployment selesai!"